---
# This is currently manually deployed.

name: bosh-worker

releases:
- name: concourse
  version: 7.8.2

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest

instance_groups:
- name: bosh-worker
  instances: 1
  vm_type: worker
  stemcell: jammy
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: worker
    release: concourse
    properties:
      team: main
      tags: [bosh]

      baggageclaim:
        driver: overlay

      drain_timeout: 10m

      worker_gateway:
        hosts: ["ci.concourse-ci.org:2222"]
        rebalance_interval: 30m

        # manually entered into bbl credhub
        # credhub set -n /bosh-{bbl env-id}/{deployment name}/worker_key -t rsa -p private_key_file -u pub_key_file
        # credhub set -n /bosh-{bbl env-id}/{deployment name}/host_public_key -t value -v "host_public_key_value"
        # when deploying, grab the current creds by running `bosh -d bosh-worker manifest > current.yml`
        # and copying the secrets to a vars-store file.
        host_public_key: ((host_public_key))
        worker_key: ((worker_key))

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 6
  serial: false
  update_watch_time: 1000-60000
