---
# This is currently manually deployed.

name: bosh-worker

releases:
- name: concourse
  version: 7.7.0

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: bosh-worker
  instances: 2
  vm_type: worker
  stemcell: xenial
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: worker
    release: concourse
    properties:
      team: main
      tags: [bosh]

      baggageclaim:
        driver: overlay

      drain_timeout: 10m

      worker_gateway:
        hosts: ["ci.concourse-ci.org:2222"]
        rebalance_interval: 30m

        # manually entered into bbl credhub by vito
        # when deploying, grab the current creds by running `bosh -d bosh-worker manifest > current.yml`
        # and copying the secrets to a vars-store file.
        host_public_key: ((host_public_key))
        worker_key: ((worker_private_key))

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 6
  serial: false
  update_watch_time: 1000-60000
