---
name: uaa

update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000

instance_groups:
- name: uaa
  azs:
  - z1
  instances: 1
  vm_type: uaa
  persistent_disk_type: large
  stemcell: default
  networks:
  - name: test
  vm_extensions:
  - concourse-uaa
  jobs:
  - name: uaa
    release: uaa
    properties:
      encryption:
        active_key_label: 'key-1'
        encryption_keys:
          - label: 'key-1'
            passphrase: 'MY-PASSPHRASE'
          - label: 'key-2'
            passphrase: 'MY-PASSPHRASE-TWO'
      login:
        saml:
          serviceProviderKey: "((uaa_login_saml.private_key))"
          serviceProviderCertificate: "((uaa_login_saml.certificate))"
      uaa:
        clients:
          admin:
            authorized-grant-types: client_credentials
            scope: uaa.none
            authorities: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin
            secret: "((uaa_admin_client_secret))"
        jwt:
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: "((uaa_jwt_signing_key.private_key))"
        scim:
          user:
            override: true
          users:
            - name: admin
              password: "((cf_admin_password))"
              groups:
                - uaa.admin
            - name: marissa
              password: koala
              groups:
                - uaa.user
        sslCertificate: "((uaa_ssl.certificate))"
        sslPrivateKey: "((uaa_ssl.private_key))"
        url: https://uaa-wings.concourse-ci.org
      uaadb:
        address: 104.154.192.148
        tls: disabled
        databases:
        - name: uaadb
          tag: uaa
        db_scheme: postgresql
        port: 5524
        roles:
        - name: uaaadmin
          password: ((uaaadmin-password))
          tag: admin
  - name: bpm
    release: bpm

variables:
- name: uaa_ca
  type: certificate
  options:
    is_ca: true
    common_name: uaaCA
- name: uaa_ssl
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa-wings.concourse-ci.org
    alternative_names:
    - uaa-wings.concourse-ci.org
- name: uaa_login_saml
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa_login_saml
- name: uaa_admin_client_secret
  type: password
- name: cf_admin_password
  type: password
- name: uaa_jwt_signing_key
  type: rsa

releases:
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=54
  version: "54"
  sha1: aa61f0013aa4c42d84cec2fcdac6cf548950011e
- name: bpm
  version: 1.0.4
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
