---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: enable_ssh
    release: windows-utilities
  - name: worker-windows
    properties:
      worker_gateway:
        hosts: ["ci.concourse-ci.org:2222"]
        host_public_key: ((host_public_key))
        worker_key:
          private_key: ((worker_private_key))
          public_key: ((worker_public_key))
    release: concourse
  name: windows-worker
  networks:
  - name: windows
  stemcell: windows
  vm_type: worker

name: concourse-prod-windows-worker
releases:
- name: concourse
  version: "5.7.0"
  url: "https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=5.7.0"
  sha1: "7fa513c5059c44eb5cc57c1fc5aaf9f845112bf3"
- name: windows-utilities
  sha1: efc10ac0f4acae23637ce2c6f864d20df2e3a781
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0
  version: 0.11.0
stemcells:
- alias: windows
  os: windows2016
  version: '1709.21'
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
