---
name: concourse-wings

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest
- name: telegraf-agent
  version: latest
- name: syslog
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

addons:
- name: syslog_forwarder
  include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
  jobs:
  - name: syslog_forwarder
    release: syslog
    properties:
      syslog:
        address: logs5.papertrailapp.com
        custom_rule: 'if ($programname startswith "vcap.") then stop

'
        permitted_peer: "*.papertrailapp.com"
        port: 40515
        tls_enabled: true
        transport: tcp

instance_groups:
- name: web
  instances: 4
  vm_type: web
  stemcell: xenial
  networks: [{name: web}]
  azs: [z1]
  vm_extensions: [wings-web-target-pool]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: "https://wings.pivotal.io"

      bind_port: 80
      tls_bind_port: 443

      log_level: debug

      encryption_key: ((encryption_key))
      token_signing_key: ((token_signing_key))

      gc_worker_concurrency: 1000

      container_placement_strategy: random

      github_auth:
        client_id: ((github_client_id))
        client_secret: ((github_client_secret))

      add_local_users:
      - "admin:((admin_password))"

      main_team:
        auth:
          github:
            teams: ["concourse:pivotal"]

      postgresql:
        host: 104.198.42.60
        ca_cert: ((db_ca_cert.certificate))
        database: atc
        role:
          name: atc
          password: ((db_password))

      influxdb:
        url: http://10.2.0.2:8086
        database: wings
        username: concourse
        password: concourse

      tls_cert: ((atc_tls.certificate))
      tls_key: ((atc_tls.private_key))

  - name: tsa
    release: concourse
    properties:
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorize_generated_worker_key: false
      authorized_keys: [((worker_key.public_key))]
      team_authorized_keys:
      - team: cf-identity-uaa
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvh2uClwWSGIUjvYj5pBe31X/nAYfcS3qFEO8vIdeE0mdBX1Ag84pKp8vudGb7YnaJP6U63xhONI26BwT086VATunFFCdbTO8SPd8Jdj3dumNeNALD8PRKo/JVbICQ7vQs07MSCpUK9p+TK1GJ1BnrPgNtsd/NvjqZr14GqZ7FHojzDpxyJZUxxLkIgm4cVh49sUoddrBj/K+2lSKN5c/1ovbeOM4hqfucOEofXImZPOZv8GneICT02fDHO4cDU2zUPUv3UCwsW+Li1K7nAdNEg6QkCuqkx1V3tZrDjvyNdclaDr4ExzFHg3sUcrwOKKmjST7ZTEMbyOPDN22gfKpX

      - team: network-integrations
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5dFYQGb165WNrTABjutqc+YLfArZS+00krefQG5d46tdhFZ7SxWnZqPw5s2O9XDwFKfc9MeFNG80WTUMH28qc0m6YDagnwT64xcF6hYshxen/hClv8IIAHX0mS/TSpDl/KMB+TEUMz8fW5v2/GxNDRZqH/ird6z7JLwuh1N9qUT/LKLW091miZcWb6Dnr86aXg076ROgBxb2a+pIRSg+/Peinqb6cRMuN/pMMd3HQBZVlaVIWM3bk094kNFoqlHgZxttkOR9IbS+bs7NqKFK8IrST25H/KDMQ865dqBIpeJU4tVI/SbON8jAHHp6w01TWmbmKkpO/o/eKgEhnkqS/ sparameswaran@Sabhas-MacBook-Pro.local

      - team: toolsmiths
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD0+KlORaq+60vBO2ZU2ZttXtHk9Kgxr2TrufyrYXpNXSmnZWU8SEssj2TbI6wqCtHEdns0NZVCb1RABj+PVMVbCwwAPBuC8hQLiKQENXJE57Em1fiIy245rnphHzLxkvq1e6PAA0x1Vg4hyZHhJ78rhoxX/06X52Lc+5ED0zuD58jrlztJlslYejxuTTz9b1XxSBG3Z3IKWmrs3PssjF9bvOSczqfOMfa7xEBFziCUIe/8YDLg6Tb8d1cEbJWl9yfqX2+4kcmbYC0KOdOmL6BznunfUjkmF/a56aWS2y0cWLDnZZiU2JKJ/ObPKWkZpeT7jbDCZb1aDndLZlahBSgz

      - team: cf-cli
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDE8EwSnKVgwLYfftCOoEEOEs1x4+TkV2nhEXuLdwdiHBngvAZMVp7jnjrJbUJVjjpcljgdtW7eP0TAlz3NMTaZfXjk3p42IrwlvoOciGcdnYFCc9BTsWgZz+urTIAFzziRC1A3yev7Hm/WGIYeVj4uq/dq1YJR6+CAsmOC1cex1eHvnUPspjpMMVzhoCqMcrTrKBLMAvS2wWr7amiXewNSNseM7Jsx3iKbyIYVZ+OznCSB0f4d8brvByvwR50u/mbYOb9n9THPAm0gKtF4wgmjM9tj3XQ7gwIuFlkmhBzFKyhHLk0zMdOacqsgmeuaO3+IYRaGskPR22TZWsqUG/6xR2ZVmtN1ITBgcnfDbEcJ6Zbqa7BZlQk66JMkJglAAWYaFaBcKJAXfE9Eaicts7cu2pHKMyHFucvrWb8798t0vw/KLdf3QypeimJBc//AEUTgZ4gpug19Aw8T6WiA2D0/Fp1KBnl72z2iOzhjkIXfP8yUWIW+LiyM/k7WlaoJNtkmMER3ggVDCpv142+3Rw0IFrE0cmgyTmYTZLNJgkjrrgO2VjxMUzyODZZdvL9TEc7oNGOPpcF4HDZB6kM45yBGQhLazLN2mRlS8Vm1MsrEccYh1epqPo+JAYNiccB0lq11gtMX4bjDF6eClVfEIs2GstANKIcPtObZ2lElHBIV8w== pivotal@natoma.sf.pivotallabs.com
      - team: cf-cli
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9TG1T7iEcaJDbvi8cnCexM3cX+/EewPip6NsHMUt/HoMOhy5n+Fr2mM+lFJ8PeUWFLgAxo2TI/JlxGDRdN66L7gHnUEM8bB8RPxfRDKEVQ5/rra9KZULJVIMmU2vNWDLb+/2LtCA6Ylf1nDYErA6sJuHkyMNRr1fFrfwT81vc+0Y9uDrHL+ENuPOccOzzWQCF3XWjS4KtRYrc0oyaj2OYjhf8fiT5KUAQKYRXUyDgZtHRGuhLf3R5dDFBIIuPSDyNruEaeYsPIohfhiOqBaJ9wpj2oxQHZRXvza69nUHBtblPnPqEU5DMn2Lw2qDLSEAwSsNC4tWxCuWYJbsb3bFYOJauJPfAtdQJKeJpkI/nb62DOOoP2PhkbdpAOcQqyZ1sAcm1F+qzMEP7V5Um8z/cVzCaD0kmzzLmLowIN8rvw4vEhSy6u1k4jCD9b4ys9LDHJTnv/FKdZYj2XGuu6lyWUxgEnTtL+CX8KPsMkPIWcCeOZdYn+pOXt8Ylh6AbwP+LmorSPKxoQucGeXAk9X//E124ZhFewU5ga3Qp+e/9jV1DEQNqGh1RymdxRB06uooqFWdg89/4Hs97wbPzhDfwqqGuMRkFjHeqHPHHaiN4tmdmOgkMap0wzpNvg0mIeELi/a6uKJ2dHJJg0LswrVu30OHprsmEnc3EQzDqZ6HXjw== CF CLI Team Concourse Worker 11-18-2016

      - team: cf-infrastructure
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRdY1LIVsWMYaSE0Ta13J+czD90jtB6E17DFJtDK0iUbdsGgi6NFnLCF16IOoc43H9zOYoHrsrb0zxW4+cwmiO+l0IGsf3m2bz5OqVwkXqi9R6Mb6IfjU41he63Dp5yi7WUNK9MhE+cJ4mKGckZtqD3rl7oM1XcG6Y8phqAMG+WaaF119ghRl5fOzCP0wQi2/sXYFVbwxUFpoi2zqEJEfH3tvNWMBHy0umG1VWKAx/5k3eeRhtmvzIDuxO/92Wr1vSYE+0Z2MjN5tom+UBL3skJ/xDR0Y0N6kbwe8Ic5IG9fCWzg5D50LcRiV9PtvMzBeg5NsX5eGe9RiFMCzYuE2jqAMIlQHudyrT9Q6aGSpaZnTn5jzJOdNZkt8Gm+gQDjl7nSWB2TvGxkfYjVlhpikWAoFuSTs+pi6qma3Sxfc78Hm1VMPw+VCLK6WN729qzIvATo1rYLa51VIus5MjdwRrETC58pLjeCxye6j8yWdHAw+tikxQQ2DFaLzFAaZhA1zoMbJuAAnT+4TtsC+AfoSpnbz0lr+YC9dS969RcFG7bcQuRHSl3Xt/4YxvjPT/Gn1uvYNllK2CM6tlWD0IhrluIZYoBGA+pGyRkcugQChGnlc2NU92P26CghCDD1OySF5mpiUGoGGGkHnoT74khN85V1w/akGHz76PAUi9gg04Vw== infrastructure-ci

      - team: cf-infrastructure
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw6Dd7QuEsIgaVj5c7YNEhYgbnmUMtqy9K962ZoMYJ7ICxxechelTT+yc/ihiQkzcyQFZx4amNxOXVQ3D6MqCGoD4ca/aly2aVwEMHi6cSUHZzyt3j/qQ2twbF8D8TrZNOEsnFTc8StrlzCHlA3GERwKbJH02616JHOtijDUNBuIYG1O+Oe2l+V/Nz4E+vw4hdpHougtBJpdMrb8ySuJlHjZBOG3iD3HWuxiXlkVLGJ6wcQ2j0Nr0Ek4904IvmyoFSYSI1i6pV+s7i6SXYC3MSb3s9Vbw9jYZp/Gm5nCLo3Aw21vqaAv9KrFjFXZ7xd6kNfcabwUdrW0229LDZRAM3

      - team: services-enablement
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2rovfB4P4nSKs0fAGr7UNVnO1ocMYD3yRQNo/S4ufWZYrNqPF/7R5kDLg0VjzrQJRGZgKunPc6OTpoJwKM5zVlL0wmFtfAXclchVAvBmUxCe9QY6SXi8LkAW70C9KzkHy+DJcbs2+Xq6yKv7SsFbc5lTUHUR/Ib1mu/B3bF23AbQrnXQjKE/H9eBGDtOxn9Mhptt3zNEAcbqsrOTtu1MxMGcHGX+VqstcRZiPTKUdxavV57cP5C+1/QxJWnhbRXmIZrMtRIpfJkwX09oyjZWqPZcqbWl0n5bO9sQhzJaJITi+0Ak7sbFcIpKGqsWug4bMP4emY0skmJQcQigwyvWZ

      - team: chynfield
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMm6irMaY3DwC+8DjSQvXZSRY4ibPnB7RnkTZkqYTGmcXumeLHbCIje0qi9P8+8i2kMUdIQoHFf7D4qdSb921gFUXz6WSZkJLckbgFmN1WLSxTUofWGLyDwctsNHfqNyir00yXZio9agxSlrb+Gqh8pTYnGCdsWxORTBb3YrhQu4ZMq7B6BpZlx5jLNtcgJjWmOsVqOm+p8mpWlf+rSxdnFLOA1Zm0onaOm02TRJmcexe3wgixzDMCHG+EG5qhRdbPT+9uTcsYXCbisy+kSz8+EBp0h5HOtkvzTnh/KmovDszAWV4amNzSEWbOZLb3JbkzYeE47StLqab5SJ8rqRIR ubuntu@chynfield-haas-122-worker-1

      - team: cf-identity-sso
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnvPOxZzXMkQmVcBuCsiEcX/J6V1C18X4naWUg3eeqSmMWGu83nplcbKx3d+0q8w4cleJ53R/IMRKGXLq/NjHjeG0p9YoZuBpDgFAmEW2x+FSX5OL93s81qCAUhvznpTnk9tc8SdTJKTxToOsU3883WyRAyLEAeDSLKEfe0rxV2FNERInU/jw6qUcqQYdoZeYbM/buElXTFi/6fCZlB2mUuCARMr6N1OzDZZu3kzF0MhlWyAa8dOmM1ljuVqsft30/EMOzxuzVwzH5S9k0TxCs+ZpOrK9b72IFV7FOeXqGJXXEi2Ry0Q1wvJusYFB18zfaWkzcZ3yd93cNZkWPbIMH

      - team: platform-insights
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5eCEYB9os8sjARt2UgpDNtY9CLKB6xUZ6LfLWGWCkxf98zxeqhB8L1n2Tu/hEZha+Btf7HD15fyLgmljhSDuqIrn0I8mS1Ulk5ohk0Ofo939OTCFlJIKxy6S4DhIEkK2XOIsw2mSrEL3omxEsT2iBopwJq/b/3Ikdyr66JbESygy4Zk5CJJ6Mw6JRxJFd0BUlAHcV2a+/aCbxNPOnZUbVNfBjGh/pka0m6DHnuGxY9fhY8PZhCalSpeiyytSFWs+6d30WgepIiS1XGVsgT3t/dott8/1T60wqJLDyoxgkincC7gBH/H3/rdXnxuHe1xQThYhwOSdlAom9KIKvKQlF
      - team: platform-insights
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp58MAe/WUn9x768Br9r3A/6W1DUkygzR71gMxD0UMYsAEjoq0xVxnHo4ucmAD/mXOsmwzAAkRa2zOPhZuSPbpFfWoQdHMrlmX8W9dXzFsMjlWGBvvqo2dCcziwZuBX29fidcwIU3EZvp+e7UjVzi5kiyYwdnp8V4AykWcOmDbgwV4QQJusD/tVp3VwKS4Bj9hKz+x8xeKPA2BWeu0k798Z2Zng12ReBjzM/sx1HYoiusk1zp7lumKe1BafRnU2wV+l4D5aXVXlOZyr1DIGjC1tioOCQQ4mXkqrn7LGn4hJj1z68tGTPmT69WzVUqjKpOr9qZfjJbKByFm6Ujz6lPt

      - team: bam
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuCcQ5xHxUSCnTHUgx6mh2Cas4jiIjkkxXVGX1Yv8iNed2rgniCXmvzxYQQwp8pSnKu+phx3D/Sj7XcZ5lWHt9kjNicrJQmzP0ClWk1jxYsNFd4rcI/cCW+GZbl+g2+Wr7MR4vNQPPgnxW9jORbAKmua+vxSFd2mf/aK5WlQEuEe6PHLWPh4fi+fp5If5Ar7LM2FSmbbsC73Ga3q2Bm8CKlanPKgKOg1cBXjmANGlXosUzDgyjhe0v6aitGrHcfSg8XLo0S4KTwVloWxko0ZeeCGDHJzqeTJ151sERZmqtnsTCK0dCnMqijeLOYLMwTvXh+uuBIBeTw1RyR1nJmHtt

      - team: mormont-pcf
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyo2/1vuyuQkIwCGou5K0CtSZJQbAC0KIeDnudoML7ZyMmHkux1oRaJrQwBg4falWRspVQY7hNARA0rw8VWVOfVx8ZLq7E8K7EbxSbQvI0fQtlU/V6bUt3PJUfLIUcAI0sx2qCPlGwHxsgENVVozqUz/eS2KZIb33f5+kyZhtdfT4HoSRQk2df0XbPWMQAlooylBJjR2Gk6ng/cJO1hUu7OiSJE6MJQ0XUsTgRjbZe3YC3pF849F1TPTGWYbeIQnbG0EdxGy1ysBZSqwUcQy++KAanW4eZp1yKF3bDna/zoVl7p9Z4iPbtaZJQUo7h2xb6w6ZKi32elUdt84mRn88l

  - name: telegraf-agent
    release: telegraf-agent
    properties:
      influxdb:
        url: http://10.2.0.2:8086
        database: wings
        username: concourse
        password: concourse
      inputs:
        procstat:
          exe: atc

- name: db-metrics
  instances: 1
  vm_type: tiny
  stemcell: xenial
  networks: [{name: private}]
  azs: [z1]
  jobs:
  - name: telegraf-agent
    release: telegraf-agent
    properties:
      influxdb:
        url: http://10.2.0.2:8086
        database: concourse
        username: concourse
        password: concourse
      inputs:
        postgresql:
          address: 'postgres://atc:((db_password))@104.198.42.60/atc?sslmode=disable'
        # postgresql_extensible:
        #   address: 'postgres://atc:((db_password))@104.198.42.60/atc?sslmode=disable'
        #   outputaddress: wings
        #   queries:
        #   - measurement: "postgresql slow queries"
        #     query: |
        #       SELECT
        #         total_time / calls AS avg_time,
        #         calls,
        #         total_time,
        #         rows,
        #         100.0 * shared_blks_hit / nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent,
        #         regexp_replace(query, '[\s\t\n]+', ' ', 'g') AS query
        #       FROM pg_stat_statements
        #       WHERE query NOT LIKE '%EXPLAIN%'
        #       ORDER BY avg_time DESC LIMIT 50
        #     version: 901
        #     tags: ["query"]

- name: worker
  instances: 25
  vm_type: wings_worker
  stemcell: xenial
  networks: [{name: private}]
  azs: [z1]
  update: {max_in_flight: 10}
  jobs:
  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m
      tsa:
        worker_key: ((worker_key))
  - release: concourse
    name: baggageclaim
    properties:
      log_level: debug
      driver: btrfs
  - release: garden-runc
    name: garden
    properties:
      garden:
        network_mtu: 1460
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        dns_servers:
        - 8.8.8.8
        - 8.8.4.4

variables:
- name: token_signing_key
  type: rsa

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
