#!/bin/bash

set -e -u

projectid=cf-concourse-production
region=us-central1
zone=us-central1-f

lpass show 'Shared-Concourse/Prod GCP Key' --notes > keypair/id_rsa
chmod 0600 keypair/id_rsa

lpass show 'Shared-Concourse/Prod GCP Credentials' --notes > iaas/terraform.key.json

pushd iaas
  terraform init
  terraform apply -var projectid=${projectid} -var region=${region} -var zone=${zone}
popd

./scripts/generate-bosh-tf-vars \
  > bosh/bosh-tf-vars.yml

lpass show 'Shared-Concourse/Prod bosh-deployment-vars.yml' --notes \
  > bosh/bosh-deployment-vars.yml

bosh create-env bosh-deployment/bosh.yml \
  --state bosh/bosh-state.json \
  --vars-store bosh/bosh-generated-creds.yml \
  -o bosh-deployment/gcp/cpi.yml \
  -v director_name=concourse-prod-bosh \
  -v internal_cidr=10.0.0.0/29 \
  -v internal_gw=10.0.0.1 \
  -v internal_ip=10.0.0.6 \
  -v project_id=cf-concourse-production \
  -v zone=us-central1-a \
  -v network=bosh \
  -v subnetwork=director \
  -v tags=[director] \
  --var-file gcp_credentials_json=iaas/terraform.key.json \
  -o bosh-deployment/syslog.yml \
  -o bosh-deployment/uaa.yml \
  -o bosh-deployment/credhub.yml \
  -o bosh-deployment/local-dns.yml \
  -o bosh-deployment/external-ip-not-recommended.yml \
  -o bosh-deployment/misc/powerdns.yml \
  -v dns_recursor_ip=169.254.169.254 \
  -o bosh/ops/ci-client.yml \
  -o bosh/ops/credhub-cli-user.yml \
  -o bosh/ops/director-vm-size.yml \
  -o bosh/ops/director-disk-size.yml \
  -o bosh/ops/os-conf-users.yml \
  -o bosh/ops/uaa-external-dns.yml \
  -o bosh/ops/unset-config-server-uaa-ca.yml \
  -o bosh/ops/workers.yml \
  -l bosh/bosh-deployment-vars.yml \
  -l bosh/bosh-tf-vars.yml
