#!/bin/bash

set -e -u

projectid=cf-concourse-production
region=us-central1
zone=us-central1-a

pushd iaas
  terraform destroy -state .terraform/terraform.tfstate -var projectid=${projectid} -var region=${region} -var zone=${zone} -force
  rm .terraform/terraform.tfstate
  rm terraform.key.json
popd
