---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5

inputs:
  - name: bosh-deployment
  - name: bbl-state

run:
  path: bosh-deployment/ci/tasks/test-bosh-lite-gcp.sh
