---
# TODO: turn into an ops-file that adds uaa as another instance-group
name: uaa

update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000

instance_groups:
- name: credhub-uaa
  azs:
  - z1
  instances: 1
  vm_type: uaa
  persistent_disk_type: large
  stemcell: default
  networks:
  - name: internal-wings
  vm_extensions:
    - wings-credhub-uaa-target-pool
  jobs:
  - name: uaa
    release: uaa
    properties:
      encryption:
        active_key_label: 'key-1'
        encryption_keys:
          - label: 'key-1'
            passphrase: "((uaa_encryption_key))"
      login:
        saml:
          serviceProviderCertificate: "((uaa_login_saml.certificate))"
          serviceProviderKey: "((uaa_login_saml.private_key))"
        branding:
          company_name: "Concourse Wings"
        links:
          signup: "https://todo.local/signup_link"
      uaa:
        clients:
          admin:
            authorized-grant-types: client_credentials
            scope: uaa.none
            authorities: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin
            secret: "((uaa_admin_client_secret))"
          credhub_cli:
            authorized-grant-types: password,refresh_token
            authorities: uaa.none
            scope: credhub.read,credhub.write
            secret: "" # cli expects this to be empty
            access-token-validity: 120
            refresh-token-validity: 1800
            override: true
          concourse_client:
            authorized-grant-types: client_credentials
            authorities: uaa.none
            scope: credhub.read,credhub.write
            secret: "concourse123" #TODO: convert to secret
            access-token-validity: 120
            refresh-token-validity: 1800
            override: true
        jwt:
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: "((uaa_jwt_signing_key.private_key))"
        scim:
          users:
            - name: admin
              password: "((cf_admin_password))"
              groups:
                - uaa.admin
            - name: credhub
              password: "((credhub_user_password))"
              groups:
                - credhub.read
                - credhub.write
        sslCertificate: "((uaa_ssl.certificate))"
        sslPrivateKey: "((uaa_ssl.private_key))"
        url: https://wings-auth.concourse-ci.org:8443
      uaadb:
        address: 104.154.192.148
        tls: disabled
        databases:
        - name: uaadb
          tag: uaa
        db_scheme: postgres
        port: 5432
        roles:
        - name: uaaadmin
          password: ((uaaadmin_db_password))
          tag: admin
  - name: bpm
    release: bpm
  - name: credhub
    release: credhub
    properties:
      credhub:
        port: 8844
        tls:
          certificate: "((credhub_ssl.certificate))"
          private_key: "((credhub_ssl.private_key))"
        data_storage:
          type: postgres
          username: credhubadmin
          password: ((credhubadmin_db_password))
          host: 104.154.192.148
          port: 5432
          database: credhubdb
          require_tls: false
        authentication:
          uaa:
            ca_certs:
              - "((uaa_ssl.certificate))"
            enabled: true
            url: "https://wings-auth.concourse-ci.org:8443"
        encryption:
          keys:
            - provider_name: internal-provider
              key_properties:
                encryption_password: "((credhub_encryption_key))"
              active: true
          providers:
            - name: internal-provider
              type: internal
        authorization:
          acls:
            enabled: true
          permissions:
            - path: /*
              actors:
                - uaa-user:20775a1f-7ba5-4395-b837-bdbf42ad22e0 # This is the ID of the 'credhub' user
                - uaa-client:concourse_client
              operations:
                - read
                - write
                - delete
                - read_acl
                - write_acl


variables:
- name: uaa_ca
  type: certificate
  options:
    is_ca: true
    common_name: uaaCA
- name: uaa_ssl
  type: certificate
  options:
    ca: uaa_ca
    common_name: wings-auth.concourse-ci.org
    alternative_names:
    - wings-auth.concourse-ci.org
    - localhost
- name: uaa_login_saml
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa_login_saml
- name: uaa_encryption_key
  type: password
- name: uaa_admin_client_secret
  type: password
- name: cf_admin_password
  type: password
- name: uaa_jwt_signing_key
  type: rsa
- name: credhub_client_secret
  type: password
- name: credhub_user_password
  type: password
- name: credhub_encryption_key
  type: password
- name: credhub_ca
  type: certificate
  options:
    is_ca: true
    common_name: credhubCA
- name: credhub_ssl
  type: certificate
  options:
    ca: credhub_ca
    common_name: wings-auth.concourse-ci.org
    alternative_names:
    - wings-auth.concourse-ci.org

releases:
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=74.0.0
  version: "74.0.0"
  sha1: e47171a9013095e60b4a7d6926257a3b23c1afbe
- name: bpm
  version: 1.0.4
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
- name: "credhub"
  version: "2.5.0"
  url: "https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=2.5.0"
  sha1: "89c5ab853980fbfa4525e04851766cb3e0e3f8c5"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
